export * from './student-periods.model';
export * from './student-periods-popup.service';
export * from './student-periods.service';
export * from './student-periods-dialog.component';
export * from './student-periods-delete-dialog.component';
export * from './student-periods-detail.component';
export * from './student-periods.component';
export * from './student-periods-as-list.component';
export * from './student-periods.route';
