export * from './student-course-period.model';
export * from './student-course-period-popup.service';
export * from './student-course-period.service';
export * from './student-course-period-dialog.component';
export * from './student-course-period-delete-dialog.component';
export * from './student-course-period-detail.component';
export * from './student-course-period.component';
export * from './student-course-period-as-list.component';
export * from './student-course-period.route';
