export * from './course-applicable.model';
export * from './course-applicable-popup.service';
export * from './course-applicable.service';
export * from './course-applicable-dialog.component';
export * from './course-applicable-delete-dialog.component';
export * from './course-applicable-detail.component';
export * from './course-applicable.component';
export * from './course-applicable-as-list.component';
export * from './course-applicable.route';
