export * from './student-course-score.model';
export * from './student-course-score-popup.service';
export * from './student-course-score.service';
export * from './student-course-score-dialog.component';
export * from './student-course-score-delete-dialog.component';
export * from './student-course-score-detail.component';
export * from './student-course-score.component';
export * from './student-course-score-as-list.component';
export * from './student-course-score.route';
