export * from './contact-mechanism-purpose.model';
export * from './contact-mechanism-purpose-popup.service';
export * from './contact-mechanism-purpose.service';
export * from './contact-mechanism-purpose-dialog.component';
export * from './contact-mechanism-purpose-delete-dialog.component';
export * from './contact-mechanism-purpose-detail.component';
export * from './contact-mechanism-purpose.component';
export * from './contact-mechanism-purpose-as-list.component';
export * from './contact-mechanism-purpose.route';
