export * from './academic-periods.model';
export * from './academic-periods-popup.service';
export * from './academic-periods.service';
export * from './academic-periods-dialog.component';
export * from './academic-periods-delete-dialog.component';
export * from './academic-periods-detail.component';
export * from './academic-periods.component';
export * from './academic-periods-as-list.component';
export * from './academic-periods.route';
